#!/bin/sh
# chkconfig: 235 80 20
### BEGIN INIT INFO
# Provides:		gclogd
# Required-Start:	$network $remote_fs
# Required-Stop:	$network $remote_fs
# Default-Start:	2 3 5
# Default-Stop:		0 1 6
# Short-Description:	Geiger Counter Logger
### END INIT INFO

case "$1" in
	start)
		/usr/bin/gclog -c /etc/gclog.conf
		;;
	stop)
		/usr/bin/killall gclog
		;;
	force-reload|restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|force-reload}" >&2
		exit 3
		;;
esac

exit 0
